version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - '8000:80'
    depends_on:
      - server1
      - server2
    networks:
      - db_nw

  server1:
    build: ./server
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - db_nw

  server2:
    build: ./server
    restart: always
    depends_on:
      - mysql
      - redis
    networks:
      - db_nw

  mysql:
    image: mysql:8.0.18
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: coupons
      MYSQL_DATABASE: coupons
    networks:
      - db_nw

  redis:
    image: redis
    restart: always
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
